# Generated by Django 5.1.5 on 2025-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_diaryimage_delete_diaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='background_color',
            field=models.BigIntegerField(default=16777215),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text_color',
            field=models.BigIntegerField(default=0),
        ),
    ]
