# Generated by Django 5.2 on 2025-04-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fields_already_exist'),
    ]

    operations = [
    ]
