# Generated by Django 5.2 on 2025-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20250426_2041'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # This is a dummy migration that acknowledges the fields already exist
        # We're not actually adding these fields as they're already in the database
    ]
