from rest_framework_nested import routers
from .views import ProjectTaskViewSet

# This router will be registered under the project router in work/urls.py
# It expects 'project_pk' from the parent router.
project_task_router = routers.SimpleRouter()
project_task_router.register(r'tasks', ProjectTaskViewSet, basename='project-tasks')

# urlpatterns will be generated by the parent router including this one.