# Generated by Django 5.1.5 on 2025-02-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_page_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
