# Generated by Django 5.1.5 on 2025-05-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='status',
        ),
    ]
