# Generated by Django 5.2 on 2025-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0003_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
