# Generated by Django 5.2 on 2025-05-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0004_projecttask_status'),
    ]

    operations = [
        # This is a safety operation to ensure the status field exists
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('in_progress', 'In Progress'),
                    ('on_hold', 'On Hold'),
                    ('cancelled', 'Cancelled'),
                    ('completed', 'Completed')
                ],
                default='pending',
                max_length=15
            ),
        ),
    ]
