# Generated by Django 5.2 on 2025-05-03 15:49

from django.db import migrations, models


def update_completed_based_on_status(apps, schema_editor):
    """
    Update the completed field based on the status field for existing records
    """
    ProjectTask = apps.get_model('project_tasks', 'ProjectTask')
    for task in ProjectTask.objects.all():
        task.completed = task.status == 'completed'
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0005_auto_20250503_2119'),
    ]

    operations = [
        # The completed field already exists in the database, so we just need to update values
        migrations.RunPython(update_completed_based_on_status),
    ]
