# Generated by Django 5.1.5 on 2025-05-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_teaminvitation_unique_together_project_members_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together={('project', 'recipient_email')},
        ),
    ]
