# Generated by Django 5.2 on 2025-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('goal_reminder', 'Goal Reminder'), ('task_due', 'Task Due'), ('system', 'System Notification'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_rejected', 'Invitation Rejected'), ('project_invitation', 'Project Invitation')], max_length=20),
        ),
    ]
