# Generated by Django 5.1.5 on 2025-02-22 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
