# Generated by Django 5.1.5 on 2025-04-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_remove_task_created_at_remove_task_last_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='has_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='reminder_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
