# Generated by Django 5.1.5 on 2025-04-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_has_reminder_goal_reminder_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='has_reminder',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='reminder_date_time',
        ),
    ]
