# Generated by Django 5.1.5 on 2025-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_has_reminder_goal_reminder_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
